name: pingpong_mix
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  firebase_database: ^11.3.4
  firebase_dynamic_links: ^6.1.4
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  firebase_ui_auth: ^1.13.1
  firebase_ui_firestore: ^1.6.1
  firebase_ui_database: ^1.4.1
  firebase_ui_oauth: ^1.5.3
  go_router: ^14.3.0
  go_router_builder: ^2.7.1
  cloud_firestore: ^5.6.5
  logger: ^2.5.0
  json_theme_plus: ^6.6.3
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/profile_placeholder.png
    - assets/appainter_theme.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
